# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions/suggestions.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsuggestions/suggestions.proto\x12\x0bsuggestions\",\n\x11SuggestionRequest\x12\x17\n\x0fpurchased_books\x18\x01 \x03(\t\"\xa9\x01\n\x12SuggestionResponse\x12\x17\n\x0fsuggested_books\x18\x01 \x03(\t\x12\x46\n\x0cvector_clock\x18\x02 \x03(\x0b\x32\x30.suggestions.SuggestionResponse.VectorClockEntry\x1a\x32\n\x10VectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32g\n\x12SuggestionsService\x12Q\n\x0eGetSuggestions\x12\x1e.suggestions.SuggestionRequest\x1a\x1f.suggestions.SuggestionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions.suggestions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUGGESTIONRESPONSE_VECTORCLOCKENTRY']._options = None
  _globals['_SUGGESTIONRESPONSE_VECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_SUGGESTIONREQUEST']._serialized_start=46
  _globals['_SUGGESTIONREQUEST']._serialized_end=90
  _globals['_SUGGESTIONRESPONSE']._serialized_start=93
  _globals['_SUGGESTIONRESPONSE']._serialized_end=262
  _globals['_SUGGESTIONRESPONSE_VECTORCLOCKENTRY']._serialized_start=212
  _globals['_SUGGESTIONRESPONSE_VECTORCLOCKENTRY']._serialized_end=262
  _globals['_SUGGESTIONSSERVICE']._serialized_start=264
  _globals['_SUGGESTIONSSERVICE']._serialized_end=367
# @@protoc_insertion_point(module_scope)
