# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions/suggestions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsuggestions/suggestions.proto\x12\x0bsuggestions\",\n\x11SuggestionRequest\x12\x17\n\x0fpurchased_books\x18\x01 \x03(\t\"-\n\x12SuggestionResponse\x12\x17\n\x0fsuggested_books\x18\x01 \x03(\t2g\n\x12SuggestionsService\x12Q\n\x0eGetSuggestions\x12\x1e.suggestions.SuggestionRequest\x1a\x1f.suggestions.SuggestionResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions.suggestions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUGGESTIONREQUEST._serialized_start=46
  _SUGGESTIONREQUEST._serialized_end=90
  _SUGGESTIONRESPONSE._serialized_start=92
  _SUGGESTIONRESPONSE._serialized_end=137
  _SUGGESTIONSSERVICE._serialized_start=139
  _SUGGESTIONSSERVICE._serialized_end=242
# @@protoc_insertion_point(module_scope)
