version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html

  orchestrator:
    build:
      context: ./
      dockerfile: ./orchestrator/Dockerfile
    ports:
      - "8081:5000"
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/orchestrator/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./orchestrator/src:/app/orchestrator/src

  fraud_detection:
    build:
      context: ./
      dockerfile: ./fraud_detection/Dockerfile
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/fraud_detection/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./fraud_detection/src:/app/fraud_detection/src

  transaction_verification:
    build:
      context: ./
      dockerfile: ./transaction_verification/Dockerfile
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/transaction_verification/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./transaction_verification/src:/app/transaction_verification/src

  suggestions:
    build:
      context: ./
      dockerfile: ./suggestions/Dockerfile
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/suggestions/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./suggestions/src:/app/suggestions/src

  order_executor_1:
    build:
      context: ./
      dockerfile: ./order_executor/Dockerfile
    environment:
      - REPLICA_ID=1
      - REPLICA_PORT=50054
      - PEERS=2:order_executor_2:50055,3:order_executor_3:50056
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/order_executor/src/app.py
    volumes:
      - ./order_executor/src:/app/order_executor/src
      - ./utils:/app/utils

  order_executor_2:
    build:
      context: ./
      dockerfile: ./order_executor/Dockerfile
    environment:
      - REPLICA_ID=2
      - REPLICA_PORT=50055
      - PEERS=1:order_executor_1:50054,3:order_executor_3:50056
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/order_executor/src/app.py
    volumes:
      - ./order_executor/src:/app/order_executor/src
      - ./utils:/app/utils

  order_executor_3:
    build:
      context: ./
      dockerfile: ./order_executor/Dockerfile
    environment:
      - REPLICA_ID=3
      - REPLICA_PORT=50056
      - PEERS=1:order_executor_1:50054,2:order_executor_2:50055
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/order_executor/src/app.py
    volumes:
      - ./order_executor/src:/app/order_executor/src
      - ./utils:/app/utils

  order_queue:
    build:
      context: ./
      dockerfile: ./order_queue/Dockerfile
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/order_queue/src/app.py
    volumes:
      - ./order_queue/src:/app/order_queue/src
      - ./utils:/app/utils

  payment_service:
    build:
      context: ./
      dockerfile: ./payment_service/Dockerfile
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PORT=50058
    volumes:
      - ./payment_service/src:/app/payment_service/src
      - ./utils:/app/utils

  books_primary:
    build:
      context: ./
      dockerfile: ./books_database/Dockerfile
    environment:
      - PYTHONFILE=/app/books_database/src/app.py
      - ROLE=primary
      - BACKUPS=books_backup_1:50061,books_backup_2:50062
    volumes:
      - ./books_database/src:/app/books_database/src
      - ./utils:/app/utils

  books_backup_1:
    build:
      context: ./
      dockerfile: ./books_database/Dockerfile
    environment:
      - PYTHONFILE=/app/books_database/src/app.py
      - ROLE=backup
      - PORT=50061
    volumes:
      - ./books_database/src:/app/books_database/src
      - ./utils:/app/utils

  books_backup_2:
    build:
      context: ./
      dockerfile: ./books_database/Dockerfile
    environment:
      - PYTHONFILE=/app/books_database/src/app.py
      - ROLE=backup
      - PORT=50062
    volumes:
      - ./books_database/src:/app/books_database/src
      - ./utils:/app/utils

  observability:
    image: grafana/otel-lgtm
    ports:
      - "3000:3000"    # Grafana UI
      - "4317:4317"    # gRPC OTLP
      - "4318:4318"    # HTTP OTLP
    environment:
      - OTEL_METRIC_EXPORT_INTERVAL=1000

