# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15payment_service.proto\x12\x0fpayment_service\"P\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nbook_title\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xc7\x01\n\x0ePaymentService\x12<\n\x0cPrepareOrder\x12\x16.payment_service.Order\x1a\x14.payment_service.Ack\x12;\n\x0b\x43ommitOrder\x12\x16.payment_service.Order\x1a\x14.payment_service.Ack\x12:\n\nAbortOrder\x12\x16.payment_service.Order\x1a\x14.payment_service.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDER']._serialized_start=42
  _globals['_ORDER']._serialized_end=122
  _globals['_ACK']._serialized_start=124
  _globals['_ACK']._serialized_end=146
  _globals['_PAYMENTSERVICE']._serialized_start=149
  _globals['_PAYMENTSERVICE']._serialized_end=348
# @@protoc_insertion_point(module_scope)
