# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import payment_service_pb2 as payment__service__pb2


class PaymentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrepareOrder = channel.unary_unary(
                '/payment_service.PaymentService/PrepareOrder',
                request_serializer=payment__service__pb2.Order.SerializeToString,
                response_deserializer=payment__service__pb2.Ack.FromString,
                )
        self.CommitOrder = channel.unary_unary(
                '/payment_service.PaymentService/CommitOrder',
                request_serializer=payment__service__pb2.Order.SerializeToString,
                response_deserializer=payment__service__pb2.Ack.FromString,
                )
        self.AbortOrder = channel.unary_unary(
                '/payment_service.PaymentService/AbortOrder',
                request_serializer=payment__service__pb2.Order.SerializeToString,
                response_deserializer=payment__service__pb2.Ack.FromString,
                )


class PaymentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PrepareOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrepareOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareOrder,
                    request_deserializer=payment__service__pb2.Order.FromString,
                    response_serializer=payment__service__pb2.Ack.SerializeToString,
            ),
            'CommitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitOrder,
                    request_deserializer=payment__service__pb2.Order.FromString,
                    response_serializer=payment__service__pb2.Ack.SerializeToString,
            ),
            'AbortOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortOrder,
                    request_deserializer=payment__service__pb2.Order.FromString,
                    response_serializer=payment__service__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment_service.PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PrepareOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment_service.PaymentService/PrepareOrder',
            payment__service__pb2.Order.SerializeToString,
            payment__service__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CommitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment_service.PaymentService/CommitOrder',
            payment__service__pb2.Order.SerializeToString,
            payment__service__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AbortOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payment_service.PaymentService/AbortOrder',
            payment__service__pb2.Order.SerializeToString,
            payment__service__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
