# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection/fraud_detection.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%fraud_detection/fraud_detection.proto\x12\x0f\x66raud_detection\"E\n\x10InitOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\"\xb4\x01\n\x11InitOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12I\n\x0cvector_clock\x18\x03 \x03(\x0b\x32\x33.fraud_detection.InitOrderResponse.VectorClockEntry\x1a\x32\n\x10VectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\" \n\x0c\x45ventRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"\xaf\x01\n\rEventResponse\x12\x12\n\nis_success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x45\n\x0cvector_clock\x18\x03 \x03(\x0b\x32/.fraud_detection.EventResponse.VectorClockEntry\x1a\x32\n\x10VectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\xb4\x01\n\x11\x43learOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12T\n\x12\x66inal_vector_clock\x18\x02 \x03(\x0b\x32\x38.fraud_detection.ClearOrderRequest.FinalVectorClockEntry\x1a\x37\n\x15\x46inalVectorClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"$\n\x12\x43learOrderResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xdb\x02\n\x0c\x46raudService\x12R\n\tInitOrder\x12!.fraud_detection.InitOrderRequest\x1a\".fraud_detection.InitOrderResponse\x12O\n\x0e\x43heckUserFraud\x12\x1d.fraud_detection.EventRequest\x1a\x1e.fraud_detection.EventResponse\x12O\n\x0e\x43heckCardFraud\x12\x1d.fraud_detection.EventRequest\x1a\x1e.fraud_detection.EventResponse\x12U\n\nClearOrder\x12\".fraud_detection.ClearOrderRequest\x1a#.fraud_detection.ClearOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection.fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INITORDERRESPONSE_VECTORCLOCKENTRY']._options = None
  _globals['_INITORDERRESPONSE_VECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_EVENTRESPONSE_VECTORCLOCKENTRY']._options = None
  _globals['_EVENTRESPONSE_VECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_CLEARORDERREQUEST_FINALVECTORCLOCKENTRY']._options = None
  _globals['_CLEARORDERREQUEST_FINALVECTORCLOCKENTRY']._serialized_options = b'8\001'
  _globals['_INITORDERREQUEST']._serialized_start=58
  _globals['_INITORDERREQUEST']._serialized_end=127
  _globals['_INITORDERRESPONSE']._serialized_start=130
  _globals['_INITORDERRESPONSE']._serialized_end=310
  _globals['_INITORDERRESPONSE_VECTORCLOCKENTRY']._serialized_start=260
  _globals['_INITORDERRESPONSE_VECTORCLOCKENTRY']._serialized_end=310
  _globals['_EVENTREQUEST']._serialized_start=312
  _globals['_EVENTREQUEST']._serialized_end=344
  _globals['_EVENTRESPONSE']._serialized_start=347
  _globals['_EVENTRESPONSE']._serialized_end=522
  _globals['_EVENTRESPONSE_VECTORCLOCKENTRY']._serialized_start=260
  _globals['_EVENTRESPONSE_VECTORCLOCKENTRY']._serialized_end=310
  _globals['_CLEARORDERREQUEST']._serialized_start=525
  _globals['_CLEARORDERREQUEST']._serialized_end=705
  _globals['_CLEARORDERREQUEST_FINALVECTORCLOCKENTRY']._serialized_start=650
  _globals['_CLEARORDERREQUEST_FINALVECTORCLOCKENTRY']._serialized_end=705
  _globals['_CLEARORDERRESPONSE']._serialized_start=707
  _globals['_CLEARORDERRESPONSE']._serialized_end=743
  _globals['_FRAUDSERVICE']._serialized_start=746
  _globals['_FRAUDSERVICE']._serialized_end=1093
# @@protoc_insertion_point(module_scope)
