# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books_database/books_database.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#books_database/books_database.proto\x12\x0e\x62ooks_database\"\x1c\n\x0bReadRequest\x12\r\n\x05title\x18\x01 \x01(\t\"\x1d\n\x0cReadResponse\x12\r\n\x05stock\x18\x01 \x01(\x05\"0\n\x0cWriteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"/\n\x0cStockRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"3\n\rStockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tremaining\x18\x02 \x01(\x05\x32\xe7\x01\n\rBooksDatabase\x12\x41\n\x04Read\x12\x1b.books_database.ReadRequest\x1a\x1c.books_database.ReadResponse\x12\x44\n\x05Write\x12\x1c.books_database.WriteRequest\x1a\x1d.books_database.WriteResponse\x12M\n\x0e\x44\x65\x63rementStock\x12\x1c.books_database.StockRequest\x1a\x1d.books_database.StockResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_database.books_database_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _READREQUEST._serialized_start=55
  _READREQUEST._serialized_end=83
  _READRESPONSE._serialized_start=85
  _READRESPONSE._serialized_end=114
  _WRITEREQUEST._serialized_start=116
  _WRITEREQUEST._serialized_end=164
  _WRITERESPONSE._serialized_start=166
  _WRITERESPONSE._serialized_end=198
  _STOCKREQUEST._serialized_start=200
  _STOCKREQUEST._serialized_end=247
  _STOCKRESPONSE._serialized_start=249
  _STOCKRESPONSE._serialized_end=300
  _BOOKSDATABASE._serialized_start=303
  _BOOKSDATABASE._serialized_end=534
# @@protoc_insertion_point(module_scope)
