# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import books_database_pb2 as books__database_dot_books__database__pb2


class BooksDatabaseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Read = channel.unary_unary(
                '/books_database.BooksDatabase/Read',
                request_serializer=books__database_dot_books__database__pb2.ReadRequest.SerializeToString,
                response_deserializer=books__database_dot_books__database__pb2.ReadResponse.FromString,
                )
        self.Write = channel.unary_unary(
                '/books_database.BooksDatabase/Write',
                request_serializer=books__database_dot_books__database__pb2.WriteRequest.SerializeToString,
                response_deserializer=books__database_dot_books__database__pb2.WriteResponse.FromString,
                )
        self.DecrementStock = channel.unary_unary(
                '/books_database.BooksDatabase/DecrementStock',
                request_serializer=books__database_dot_books__database__pb2.StockRequest.SerializeToString,
                response_deserializer=books__database_dot_books__database__pb2.StockResponse.FromString,
                )
        self.ReplicateWrite = channel.unary_unary(
                '/books_database.BooksDatabase/ReplicateWrite',
                request_serializer=books__database_dot_books__database__pb2.WriteRequest.SerializeToString,
                response_deserializer=books__database_dot_books__database__pb2.WriteResponse.FromString,
                )


class BooksDatabaseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecrementStock(self, request, context):
        """Bonus atomic operation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateWrite(self, request, context):
        """Replication to backups
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BooksDatabaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=books__database_dot_books__database__pb2.ReadRequest.FromString,
                    response_serializer=books__database_dot_books__database__pb2.ReadResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=books__database_dot_books__database__pb2.WriteRequest.FromString,
                    response_serializer=books__database_dot_books__database__pb2.WriteResponse.SerializeToString,
            ),
            'DecrementStock': grpc.unary_unary_rpc_method_handler(
                    servicer.DecrementStock,
                    request_deserializer=books__database_dot_books__database__pb2.StockRequest.FromString,
                    response_serializer=books__database_dot_books__database__pb2.StockResponse.SerializeToString,
            ),
            'ReplicateWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateWrite,
                    request_deserializer=books__database_dot_books__database__pb2.WriteRequest.FromString,
                    response_serializer=books__database_dot_books__database__pb2.WriteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'books_database.BooksDatabase', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BooksDatabase(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books_database.BooksDatabase/Read',
            books__database_dot_books__database__pb2.ReadRequest.SerializeToString,
            books__database_dot_books__database__pb2.ReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books_database.BooksDatabase/Write',
            books__database_dot_books__database__pb2.WriteRequest.SerializeToString,
            books__database_dot_books__database__pb2.WriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DecrementStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books_database.BooksDatabase/DecrementStock',
            books__database_dot_books__database__pb2.StockRequest.SerializeToString,
            books__database_dot_books__database__pb2.StockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplicateWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books_database.BooksDatabase/ReplicateWrite',
            books__database_dot_books__database__pb2.WriteRequest.SerializeToString,
            books__database_dot_books__database__pb2.WriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
