# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import order_queue_pb2 as order__queue_dot_order__queue__pb2


class OrderQueueServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enqueue = channel.unary_unary(
                '/order_queue.OrderQueueService/Enqueue',
                request_serializer=order__queue_dot_order__queue__pb2.OrderRequest.SerializeToString,
                response_deserializer=order__queue_dot_order__queue__pb2.EnqueueResponse.FromString,
                )
        self.Dequeue = channel.unary_unary(
                '/order_queue.OrderQueueService/Dequeue',
                request_serializer=order__queue_dot_order__queue__pb2.Empty.SerializeToString,
                response_deserializer=order__queue_dot_order__queue__pb2.DequeueResponse.FromString,
                )


class OrderQueueServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Enqueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dequeue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderQueueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enqueue': grpc.unary_unary_rpc_method_handler(
                    servicer.Enqueue,
                    request_deserializer=order__queue_dot_order__queue__pb2.OrderRequest.FromString,
                    response_serializer=order__queue_dot_order__queue__pb2.EnqueueResponse.SerializeToString,
            ),
            'Dequeue': grpc.unary_unary_rpc_method_handler(
                    servicer.Dequeue,
                    request_deserializer=order__queue_dot_order__queue__pb2.Empty.FromString,
                    response_serializer=order__queue_dot_order__queue__pb2.DequeueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'order_queue.OrderQueueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderQueueService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Enqueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order_queue.OrderQueueService/Enqueue',
            order__queue_dot_order__queue__pb2.OrderRequest.SerializeToString,
            order__queue_dot_order__queue__pb2.EnqueueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Dequeue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order_queue.OrderQueueService/Dequeue',
            order__queue_dot_order__queue__pb2.Empty.SerializeToString,
            order__queue_dot_order__queue__pb2.DequeueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
