# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transaction_verification_pb2 as transaction__verification_dot_transaction__verification__pb2


class TransactionVerificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitOrder = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/InitOrder',
                request_serializer=transaction__verification_dot_transaction__verification__pb2.InitOrderRequest.SerializeToString,
                response_deserializer=transaction__verification_dot_transaction__verification__pb2.InitOrderResponse.FromString,
                )
        self.CheckBooks = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/CheckBooks',
                request_serializer=transaction__verification_dot_transaction__verification__pb2.EventRequest.SerializeToString,
                response_deserializer=transaction__verification_dot_transaction__verification__pb2.EventResponse.FromString,
                )
        self.CheckUserFields = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/CheckUserFields',
                request_serializer=transaction__verification_dot_transaction__verification__pb2.EventRequest.SerializeToString,
                response_deserializer=transaction__verification_dot_transaction__verification__pb2.EventResponse.FromString,
                )
        self.CheckCardFormat = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/CheckCardFormat',
                request_serializer=transaction__verification_dot_transaction__verification__pb2.EventRequest.SerializeToString,
                response_deserializer=transaction__verification_dot_transaction__verification__pb2.EventResponse.FromString,
                )
        self.ClearOrder = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/ClearOrder',
                request_serializer=transaction__verification_dot_transaction__verification__pb2.ClearOrderRequest.SerializeToString,
                response_deserializer=transaction__verification_dot_transaction__verification__pb2.ClearOrderResponse.FromString,
                )


class TransactionVerificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserFields(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckCardFormat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionVerificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitOrder,
                    request_deserializer=transaction__verification_dot_transaction__verification__pb2.InitOrderRequest.FromString,
                    response_serializer=transaction__verification_dot_transaction__verification__pb2.InitOrderResponse.SerializeToString,
            ),
            'CheckBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBooks,
                    request_deserializer=transaction__verification_dot_transaction__verification__pb2.EventRequest.FromString,
                    response_serializer=transaction__verification_dot_transaction__verification__pb2.EventResponse.SerializeToString,
            ),
            'CheckUserFields': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserFields,
                    request_deserializer=transaction__verification_dot_transaction__verification__pb2.EventRequest.FromString,
                    response_serializer=transaction__verification_dot_transaction__verification__pb2.EventResponse.SerializeToString,
            ),
            'CheckCardFormat': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckCardFormat,
                    request_deserializer=transaction__verification_dot_transaction__verification__pb2.EventRequest.FromString,
                    response_serializer=transaction__verification_dot_transaction__verification__pb2.EventResponse.SerializeToString,
            ),
            'ClearOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearOrder,
                    request_deserializer=transaction__verification_dot_transaction__verification__pb2.ClearOrderRequest.FromString,
                    response_serializer=transaction__verification_dot_transaction__verification__pb2.ClearOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transaction_verification.TransactionVerificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransactionVerificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerificationService/InitOrder',
            transaction__verification_dot_transaction__verification__pb2.InitOrderRequest.SerializeToString,
            transaction__verification_dot_transaction__verification__pb2.InitOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerificationService/CheckBooks',
            transaction__verification_dot_transaction__verification__pb2.EventRequest.SerializeToString,
            transaction__verification_dot_transaction__verification__pb2.EventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckUserFields(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerificationService/CheckUserFields',
            transaction__verification_dot_transaction__verification__pb2.EventRequest.SerializeToString,
            transaction__verification_dot_transaction__verification__pb2.EventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckCardFormat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerificationService/CheckCardFormat',
            transaction__verification_dot_transaction__verification__pb2.EventRequest.SerializeToString,
            transaction__verification_dot_transaction__verification__pb2.EventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transaction_verification.TransactionVerificationService/ClearOrder',
            transaction__verification_dot_transaction__verification__pb2.ClearOrderRequest.SerializeToString,
            transaction__verification_dot_transaction__verification__pb2.ClearOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
