# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_executor/order_executor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#order_executor/order_executor.proto\x12\x0eorder_executor\"%\n\x0f\x45lectionRequest\x12\x12\n\nreplica_id\x18\x01 \x01(\x05\"6\n\x10\x45lectionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tleader_id\x18\x02 \x01(\x05\"\"\n\x0cOrderRequest\x12\x12\n\nreplica_id\x18\x01 \x01(\x05\"\x1f\n\rOrderResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x8a\x02\n\x14OrderExecutorService\x12R\n\rStartElection\x12\x1f.order_executor.ElectionRequest\x1a .order_executor.ElectionResponse\x12Q\n\x0cNotifyLeader\x12\x1f.order_executor.ElectionRequest\x1a .order_executor.ElectionResponse\x12K\n\x0c\x44\x65queueOrder\x12\x1c.order_executor.OrderRequest\x1a\x1d.order_executor.OrderResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor.order_executor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ELECTIONREQUEST._serialized_start=55
  _ELECTIONREQUEST._serialized_end=92
  _ELECTIONRESPONSE._serialized_start=94
  _ELECTIONRESPONSE._serialized_end=148
  _ORDERREQUEST._serialized_start=150
  _ORDERREQUEST._serialized_end=184
  _ORDERRESPONSE._serialized_start=186
  _ORDERRESPONSE._serialized_end=217
  _ORDEREXECUTORSERVICE._serialized_start=220
  _ORDEREXECUTORSERVICE._serialized_end=486
# @@protoc_insertion_point(module_scope)
